version: "3.8"

services: 
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=1
      - SA_PASSWORD=Password123
      - MSSQL_USER=sa
      - MSSQL_PID=Developer
